services:
  - type: web
    name: aldimi-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn ALDIMI_API.main:app --host 0.0.0.0 --port $PORT"
